export interface EmendaFormI {
  emenda_id?: number;
  emenda_cadastro_tipo_id?: number;
  emenda_cadastro_id?: number;
  emenda_autor_nome?: string;
  emenda_situacao_id?: number;
  emenda_numero?: string;
  emenda_funcional_programatica?: string;
  emenda_orgao_solicitado_nome?: string;
  emenda_numero_protocolo?: string;
  emenda_assunto_id?: number;
  emenda_data_solicitacao?: string;
  emenda_processo?: string;
  emenda_tipo_emenda_id?: number;
  emenda_ogu_id?: number;
  emenda_valor_solicitadado?: number;
  emenda_valor_empenhado?: number;
  emenda_data_empenho?: string;
  emenda_numero_empenho?: string;
  emenda_crnr?: string;
  emenda_gmdna?: string;
  emenda_observacao_pagamento?: string;
  emenda_observacao_pagamento_delta?: string;
  emenda_observacao_pagamento_texto?: string;
  emenda_data_pagamento?: string;
  emenda_valor_pago?: number;
  emenda_numero_ordem_bancaria?: string;
  emenda_justificativa?: string;
  emenda_justificativa_delta?: string;
  emenda_justificativa_texto?: string;
  emenda_local_id?: number;
  emenda_uggestao?: string;
  emenda_siconv?: string;
  // emenda_regiao_id?: number;
  emenda_contrato?: string;
  emenda_porcentagem?: number;
  // cadastro_cpfcnpj?: string;
  // cadastro_municipio_nome?: string;
  historico_andamento?: string;
  historico_andamento_delta?: string;
  historico_andamento_texto?: string;
}

export class EmendaForm implements EmendaFormI {
  emenda_id?: number;
  emenda_cadastro_tipo_id?: number;
  emenda_cadastro_id?: number;
  emenda_autor_nome?: string;
  emenda_situacao_id?: number;
  emenda_numero?: string;
  emenda_funcional_programatica?: string;
  emenda_orgao_solicitado_nome?: string;
  emenda_numero_protocolo?: string;
  emenda_assunto_id?: number;
  emenda_data_solicitacao?: string;
  emenda_processo?: string;
  emenda_tipo_emenda_id?: number;
  emenda_ogu_id?: number;
  emenda_valor_solicitadado?: number;
  emenda_valor_empenhado?: number;
  emenda_data_empenho?: string;
  emenda_numero_empenho?: string;
  emenda_crnr?: string;
  emenda_gmdna?: string;
  emenda_observacao_pagamento?: string;
  emenda_observacao_pagamento_delta?: string;
  emenda_observacao_pagamento_texto?: string;
  emenda_data_pagamento?: string;
  emenda_valor_pago?: number;
  emenda_numero_ordem_bancaria?: string;
  emenda_justificativa?: string;
  emenda_justificativa_delta?: string;
  emenda_justificativa_texto?: string;
  emenda_local_id?: number;
  emenda_uggestao?: string;
  emenda_siconv?: string;
  // emenda_regiao_id?: number;
  emenda_contrato?: string;
  emenda_porcentagem?: number;
  // cadastro_cpfcnpj?: string;
  // cadastro_municipio_nome?: string;
  historico_andamento?: string;
  historico_andamento_delta?: string;
  historico_andamento_texto?: string;
}
