export class Rule {
  static cadastro = 'ca';
  static configuracao = 'cf';
  static assunto = 'as';
  static municipio = 'mu';
  static usuario = 'us';
  static solicitacao = 'so';
  static processo = 'pr';
  static oficio = 'of';
  static historico = 'hi';
  static agenda = 'ag';
  static agenda2 = 'a2';
  static telefone = 'te';
  static contabilidade = 'co';
  static contatos = 'ct';
  static emenda = 'em';
  static historicoemenda = 'he';
  static cadastrosigilo = 'cs';
  static proposicao = 'pp';
  static andamentoproposicao = 'ap';
  static passagem = 'pa';
  static sms = 'sm';
  static arquivos = 'ar';
  static principal = 'up';
  static responsavel = 'ur';
  static tarefa = 'tf';
}
