import {ColunasI} from "../../_models/colunas-i";

export interface CadastroBuscaI {
  cadastro_id?: number;
  cadastro_tipo_id?: number;
  cadastro_nome?: string;
  cadastro_sigla?: string;
  cadastro_apelido?: string;
  cadastro_responsavel?: string;
  cadastro_cargo?: string;
  cadastro_estado_id?: number;
  cadastro_bairro?: string;
  cadastro_municipio_id?: number;
  cadastro_municipio_nome?: string;
  cadastro_regiao_id?: number;
  cadastro_regiao_nome?: string;
  cadastro_grupo_id?: number;
  cadastro_anidia?: number;
  cadastro_animes?: number;
  quinzena?: number;
  cadastro_data_nascimento1?: string;
  cadastro_data_nascimento2?: string;
  cadastro_usuario?: string;
  cadastro_estado_civil_id?: number;
  cadastro_escolaridade_id?: number;
  cadastro_profissao?: string;
  cadastro_sexo2?: string;
  cadastro_zona?: string;
  cadastro_data_cadastramento?: string;
  cadastro_jornal?: number;
  cadastro_mala?: number;
  cadastro_agenda?: number;
  cadastro_sigilo?: number;
  cadastro_cpfcnpj?: string;
  telefone?: string;
  cadastro_campo1?: string;
  cadastro_campo2?: string;
  cadastro_campo3?: string;
  cadastro_campo4_id?: number;
  rows?: number;
  first?: number;
  sortOrder?: number;
  sortField?: string;
  todos?: boolean;
  campos?: ColunasI[];
  ids?: number[];
  excel?: boolean;
}
