import { CadastroBuscaInterface } from './cadastro-busca.interface';

export class CadastroBusca implements CadastroBuscaInterface {
  cadastro_tipo = 0;
  cadastro_nome = '';
  cadastro_sigla = '';
  cadastro_apelido = '';
  cadastro_responsavel = '';
  cadastro_cargo = '';
  cadastro_estado_id = 0;
  cadastro_bairro = '';
  cadastro_municipio_id = 0;
  cadastro_municipio_nome = '';
  cadastro_regiao_id = 0;
  cadastro_regiao_nome = '';
  cadastro_grupo_id = 0;
  aniversario = '';
  anidia = '';
  quinzena = '';
  data1 = '';
  data2 = '';
  cadastro_usuario = '';
  cadastro_estado_civil_id = 0;
  cadastro_escolaridade_id = 0;
  cadastro_profissao = '';
  cadastro_sexo = '';
  cadastro_zona = '';
  cadastro_data_cadastramento = '';
  cadastro_jornal = 0;
  cadastro_mala = 0;
  cadastro_agenda = 0;
  cadastro_sigilo = 0;
  cadastro_cpfcnpj = '';
  telefone = '';
  cadastro_campo1 = '';
  cadastro_campo2 = '';
  cadastro_campo3 = '';
  cadastro_campo4_id = 0;
  numlinhas = '';
  inicio = '';
  sortorder = '';
  sortcampo = '';
  todos =  false;
  campos = [];
  ids = [];
  sms = false;
}
